spring:
#    http:
#        encoding:
#          charset: UTF-8
#          force: true
#          enabled: true
    mvc:
        static-path-pattern: /**
    resources:
        static-locations:
            - classpath:/META-INF/resources/
            - classpath:/resources/
            - classpath:/static/
            - classpath:/public/
            - file:${location.resource.static-path}
    servlet:
        multipart:
            max-file-size: 10Mb
            max-request-size: 100Mb
    thymeleaf:
        prefix: classpath:/templates/
        check-template-location: true
        suffix: .html
        encoding: UTF-8
        mode: LEGACYHTML5
        cache: false
    jpa:
        database: mysql
        show-sql: true
        open-in-view: true
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/SpringBoot_OA?characterEncoding=utf8&useUnicode=true&useSSL=true
#        url: jdbc:mysql://192.168.64.101:3306/SpringBoot_OA?characterEncoding=utf8&useUnicode=true&useSSL=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        hikari:
            pool-name: Springboot-OA-HikariCP
            connection-test-query: SELECT 1
    data:
        mongodb:
          uri: mongodb://127.0.0.1:27017
          database: spring_boot_oa
    aop:
        auto: true
        proxy-target-class: true
    jackson:
        serialization:
            indent_output: true
    cache:
        ehcache:
            config: /config/ehcache.xml
    redis:
        host: 192.168.64.104
        port: 6379
        database: 0
        password: redis
        timeout: 3000s
        jedis:
            pool:
              max-active: 50
              max-idle: 50
              max-wait: 10s
# server localhost:8888/oa/
server:
    port: 8888
    servlet:
        context-path: /oa
    tomcat:
        uri-encoding: UTF-8
        accesslog:
            enabled: true
logging:
    level:
       org.springfromework.web: info
       org.hibernate: error
       com.caolei.system.handle.GlobalExceptionHandler: error
       com.caolei.system.aop.WebLogAspect: info
    # path和file不能同时存在,如果都有则使用file
    file: ${location.resource.path}log/application.log
location:
    resource:
        path: d:/temp/
        static-path: ${location.resource.path}static/
        upload-path: ${location.resource.path}upload/
plugin:
    swagger2:
        show: false
    shiro:
        cipher-key: 4028c081645b411c01645b4127c40026
        login-retry-times: 5
        hash-algorithm-name: SHA-256
        hash-iterations: 100
        # 600 秒 重置登陆次数时间 最大为 30分钟1800
        lock-expired-time: 600
        # 259200 秒 - 30 天 记住我功能过期时间
        remember-me-age: 259200
