location:
    resource:
        base-path: c:/cloud0072/spring-boot
spring:
    jpa:
        database: h2
        show-sql: true
        open-in-view: true
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    datasource:
        url: jdbc:h2:file:${location.resource.db-path}/spring_boot_oa_db
        username: root
        password: root
        driver-class-name: org.h2.Driver
        hikari:
            pool-name: Springboot-OA-HikariCP
            connection-test-query: SELECT 1
    h2:
        console:
            settings:
                web-allow-others: true
            path: /h2
            enabled: true
    redis:
        host: 192.168.64.104
        port: 6379
        database: 0
        password: redis
        timeout: 3000s
        jedis:
            pool:
              max-active: 50
              max-idle: 50
              max-wait: 10s
logging:
    level:
       org.springfromework.web: info
       org.hibernate: error
       com.caolei.base.handle.GlobalExceptionHandler: error
       com.caolei.base.aop.WebLogAspect: info
plugin:
    swagger2:
        enable: true