# server localhost:8888/oa/
server:
    port: 8888
    servlet:
        context-path: /oa
    tomcat:
        accesslog:
          enabled: true
spring:
    resources:
        static-locations:
            - classpath:/META-INF/resources/
            - classpath:/resources/
            - classpath:/static/
            - classpath:/public/
            - file:${location.resource.static-path}/
    mvc:
        static-path-pattern: /**
    servlet:
        multipart:
            max-file-size: 10Mb
            max-request-size: 100Mb
    thymeleaf:
        prefix: classpath:/templates/
        check-template-location: true
        suffix: .html
        encoding: UTF-8
        mode: LEGACYHTML5
        cache: false
    jpa:
        database: h2
        show-sql: true
        open-in-view: true
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    datasource:
        url: jdbc:h2:file:${location.resource.db-path}/spring_boot_oa_db
        username: root
        password: root
        driver-class-name: org.h2.Driver
        hikari:
            pool-name: Springboot-OA-HikariCP
            connection-test-query: SELECT 1
    h2:
        console:
            settings:
                web-allow-others: true
            path: /h2-console
            enabled: true
    aop:
        auto: true
        proxy-target-class: true
    jackson:
        serialization:
            indent_output: true
    cache:
        ehcache:
            config: classpath:config/ehcache.xml
    redis:
        host: 192.168.64.104
        port: 6379
        database: 0
        password: redis
        timeout: 3000s
        jedis:
            pool:
              max-active: 50
              max-idle: 50
              max-wait: 10s
logging:
    level:
       org.springfromework.web: info
       org.hibernate: error
       com.caolei.base.handle.GlobalExceptionHandler: error
       com.caolei.base.aop.WebLogAspect: info
    file: ${location.resource.log-path}/application.log
location:
    resource:
        base-path: c:/caolei/spring-boot
        static-path: ${location.resource.base-path}/static
        upload-path: ${location.resource.base-path}/upload
        config-path: ${location.resource.base-path}/config
        log-path: ${location.resource.base-path}/log
        db-path: ${location.resource.base-path}/h2
plugin:
    swagger2:
        show: true
    shiro:
        cipher-key: 4028c081645b411c01645b4127c40026
        hash-algorithm-name: SHA-256
        login-retry-times: 5
        hash-iterations: 100
        lock-expired-time: 600
        remember-me-age: 259200
