location:
    resource:
        base-path: d:/spring-boot
spring:
    jpa:
        database: mysql
        show-sql: true
        open-in-view: true
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/SpringBoot_OA?characterEncoding=utf8&useUnicode=true&useSSL=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        hikari:
            pool-name: Springboot-OA-HikariCP
            connection-test-query: SELECT 1
    redis:
        host: 192.168.64.104
        port: 6379
        database: 0
        password: redis
        timeout: 3000s
        jedis:
            pool:
              max-active: 50
              max-idle: 50
              max-wait: 10s
logging:
    level:
       org.springfromework.web: info
       org.hibernate: error
       com.caolei.base.handle.GlobalExceptionHandler: error
       com.caolei.base.aop.WebLogAspect: info
